
spring:
    datasource:
#      postgresql:
#        driver-class-name: org.postgresql.Driver
#        url: jdbc:postgresql://localhost:5434/backenddb
#        username: backend
#        password: backend
#      oracle:
        driver-class-name: oracle.jdbc.OracleDriver
        url: jdbc:oracle:thin:@localhost:1521/orcl
        username: system
        password: yuwei
    jpa:
      database-platform: org.hibernate.dialect.Oracle12cDialect
      hibernate:
        ddl-auto: none
      show-sql: true
server:
  port: 9458
